name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  testAndPublish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os : [windows-latest]
        toolchain:
          - stable

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - run: cargo publish --token ${CRATES_TOKEN}
      env:
        CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
    
    
